spring:
  application:
    name: usuarios-service

  datasource:
    url: jdbc:mysql://localhost:3306/kala
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:8089
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 9091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: host.docker.internal
    instance-id: usuarios-service:${random.uuid}