spring:
  application:
    name: usuarios-service
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      name: usuarios-service
      retry:
        max-attempts: 5
        initial-interval: 2000

  kafka:
    consumer:
      bootstrap-servers: localhost:8089
      group-id: group_id
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      bootstrap-servers: localhost:8089
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      instanceId: ${spring.application.name}:${random.uuid}
